### ISSUE TITLE
Finish logo and create a lettermark

### ISSUE THREAD

**Issue by melisayu** [transpaer/transpaer#18]
**Identity**

**Concept**

**Sketch** (full logo)
![Image](https://github.com/sustainity-dev/issues/assets/48442249/5c8f8916-458d-42b0-83f2-19592b3cbc7d)

**TASKS LIST:**
- [ ] Finalize the logo. Ensure that we have high-quality digital files in various formats (e.g., PNG, SVG, AI) for different use cases.
- [ ] Create a lettermark. A Lettermark is a logo comprising an abbreviation/smaller version of full logo.
- [ ] Integrate the logo into software product, website, social media platforms, and any other brand touchpoints. 
- [ ] Gather first feedback.
